inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/OneClassPerFile:
  Exclude:
    - spec/spec_helper.rb

RSpec/SpecFilePathFormat:
  CustomTransform:
    WS2XX: ws2xx
    WebSocketClient: websocket_client